updated VPC creation file with count and dynamic count
sinhprab/terraform-in-21-days pull request #3
Opened 2023-07-23 13:13 UTC by sinhprab

2023-07-23 17:50 UTC, vladimirmukhin requested changes

2023-07-23 17:50 UTC, vladimirmukhin commented on main.tf
> +}
```suggestion
  availability_zone = ["eu-west-2a", "eu-west-2b"]
}
```

2023-07-23 17:50 UTC, vladimirmukhin commented on main.tf
> +
```suggestion
}
```

2023-07-23 17:50 UTC, vladimirmukhin commented on main.tf
>    tags = {
```suggestion
  vpc = true
  
  tags = {
```

2023-07-23 17:50 UTC, vladimirmukhin commented on main.tf
>    tags = {
```suggestion
  availability_zone = local.availability_zone[count.index]
  
  tags = {
```

2023-07-24 06:18 UTC, sinhprab commented on main.tf
> +}
Done , removed  the extra line

2023-07-24 06:18 UTC, sinhprab commented on main.tf
> +
Done , deleted  the extra line

2023-07-24 06:18 UTC, sinhprab commented on main.tf
>    tags = {
Done , added  the extra line

2023-07-24 06:18 UTC, sinhprab commented on main.tf
>    tags = {
Done , added  the extra line

2023-07-24 17:54 UTC, vladimirmukhin approved these changes

2023-07-25 06:54 UTC, merged